backend:
  name: github
  repo: sohil89/physioace
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "pubDate"
        widget: "datetime"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Body"
        name: "body"
        widget: "markdown"
